//arithmetic calculations
public  class ArithmeticCalculations {
    public integer Addition(integer x,integer y) {
        integer z = x + y;
        system.debug(z);
    }
    public integer Subtraction(integer x,integer y) {
        integer z = x - y;
        system.debug(z);
    }
    public integer Multiplication(integer x,integer y,integer m) {
        integer z = x*y*m;
        system.debug(z);
    }
}
