public class checkDatatypes {
    public void MethodBoolean() {
        Boolean checkBoolean= true;
        system.debug('checkBoolean='+checkBoolean);
    }
    public void MethodInteger() {
        Integer varfirst= 1;
        Integer varsecond= 2;
        system.debug('varfirst='+varfirst);
        system.debug('varsecond='+varsecond);
    }
    public void Stringmethod() {
        String varname= 'Name';
        String var2name= 'Esra';
        system.debug('varname='+varname);
        system.debug('var2name='+var2name);
    }
}
